# fly.toml app configuration file generated for edbotz on 2026-05-23T09:54:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'edbotz'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
